# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rkergast <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/09 16:27:32 by rkergast          #+#    #+#              #
#    Updated: 2018/11/09 16:27:40 by rkergast         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Libft.a
CC = gcc
FLAGS = -Wall -Wextra -Werror
EXEC = exe

SRC = 

all: $(EXEC)

$(EXEC):
	$(CC) -o $(FLAGS) $(SRC)

clean:
	rm -rf *.o

fclean: clean
	rm -rf $(NAME)

re: fclean $(EXEC)
